config-version = 2

start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

persistent-workspaces = ["1", "2", "3"]

[mode.main.binding]
# Switch between workspaces
ctrl-rightSquareBracket = 'workspace next'
ctrl-leftSquareBracket = 'workspace prev'

# Switch between windows in active workspace
alt-rightSquareBracket = 'focus --boundaries workspace --boundaries-action wrap-around-the-workspace right'
alt-leftSquareBracket = 'focus --boundaries workspace --boundaries-action wrap-around-the-workspace left'

# Switch to workspace by number
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'

# Move focused window to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
